---
title: "Statistical Analysis of Bike Sharing Data"
output:
  pdf_document: default
  html_document:
    highlight: tango
    number_sections: yes
    theme: journal
---
```{r setup, include=TRUE}
knitr::opts_chunk$set(cache=FALSE)
knitr::opts_chunk$set(echo=TRUE)
knitr::opts_chunk$set(fig.width=14)
knitr::opts_chunk$set(fig.height=14)
prjpath <- "~/work/citiviz/bikeSharing/bikestats/"
datapath <- paste(prjpath, "data/", sep="")
analpath <- paste(prjpath, "analyses/", sep="")
rcodepath <- paste(analpath, "Rcode/", sep="")
setwd(analpath)
```

#Abstract
In this report we develop statistical analysis that can be applied to bike sharing data. The goal of this analysis is to  1: understand the nature of bike usage in a bike sharing system, from  angles of users, the providers of the bike sharing system, and the city where the bike sharing system is situated, 2: define and quantify the performance of a bike sharing system,  3: suggest improvements to the system's performance, and 4. to develop our analysis into visualizations for the end user who can be the bike sharing system providers, the city, or the users of the bike sharing system. To stengthen our analysis we have used example data form online resources, in addition to the data provided by the bike sharing company.


#Introduction
Several bike sharing systems have started recently in different parts of the world. Because it is geographically distributed, and used  both as well as use by the bikers, it is hard to define a performance metric for a bike sharing system. We study the usage patterns across the users (bikers), and across the stations to define several consistent, quantitative metrics that measures the performance of the system. Such  metrics will allow us to study the performance when some changes are made to the system, such as the addition or removal of a bike station.  

We consider several viewpoints of the bike sharing system (BSS), which will be addressed  as independent analysis of the data,

1. __systemic perspective__: an analysis of the overall usage of the system
2. __user perspective__: an analysis of the user behavior
3. __station perspective__: an analysis of the usage of bike stations
4. __business perspective__: an analysis of how the usage translates into revenue
5. __geospatial perspective__: an analysis of the geospatial features of the BSS network
6. __operational perspective__: an analysis of the operations involved in running a BSS network
7. __multimodal transport perspective__: an analysis of how the BSS is situated in the larger multi-modal transportation network of the city
